title: DMs of Vancouver
email: dmsofvancouver@gmail.com

description: > # this means to ignore newlines until "baseurl:"
  DMs of Vancouver is a podcast for new and vetran DMs. We go over a variety
  of topics, trying to give good advice on what a DM will encounter as they run games
  for their players.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dmsofvancouver.ca"
highlighter: rouge
permalink: pretty

google_analytics: "UA-99453135-1"

podcast:
  subtitle: "The D&D podcast for new & veteran DMs"
  image: "/podcast-image.png"
  author:
    name: DMs of Vancouver (Jessy Boros & Sean Hagen)
    email: dmsofvancouver@gmail.com

collections:
  episodes:
    output: true
    permalink: /:collection/:year/:month/:day/:title/
  articles:
    output: true
    permalink: /:collection/:year/:month/:day/:title/

navigation:
  - title: About
    url: /about/
  - title: Episodes
    url: /episodes/
  - title: Articles
    url: /articles/
  - title: Archive
    url: /archive/

pagination:
  enabled: true
  debug: true
  collection: 'articles'
  per_page: 10
  permalink: '/p:num.html'
  sort_field: 'date'
  sort_reverse: true

autopages:
  enabled: true
  tags:
    enabled: false
  categories:
    enabled: false
  collections:
    enabled: true
    layouts:
      - 'autopage_collection.html'
    title: 'Posts in :coll'
    permalink: '/:coll/'

social:
  twitter: dmsofvancouver
  facebook: groups/dmsofvancouver
  email: dmsofvancouver@gmail.com

# Build settings
markdown: kramdown
theme: minima

gems:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-sitemap
  # - jekyll-paginate-category

exclude:
  - [vendor]
  - s3_website.yml
  - README.md
  - package.json
  - gulpfile.js
  - node_modules
  - Gemfile
  - Gemfile.lock
